spring:
  application:
    name: "Core Demo Application"
  profiles:
    active: dev, petrol #ovveride this with java -jar java-path-spring-core\target\java-path-spring-core-2021.1.0.jar
                        # --spring.profiles.active=dev
myproperties:
  threadPool: 40
  email: example@development.com
  servers:
    - www.abc.dev.com
    - www.xyz.dev.com
